#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : optipng
Version  : 0.7.7
Release  : 3
URL      : https://sourceforge.net/projects/optipng/files/OptiPNG/optipng-0.7.7/optipng-0.7.7.tar.gz
Source0  : https://sourceforge.net/projects/optipng/files/OptiPNG/optipng-0.7.7/optipng-0.7.7.tar.gz
Summary  : zlib compression library
Group    : Development/Tools
License  : BSL-1.0 GPL-2.0 Libpng Zlib
Requires: optipng-bin = %{version}-%{release}
Requires: optipng-license = %{version}-%{release}
Requires: optipng-man = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : libpng-dev
BuildRequires : zlib-dev
Patch1: 0001-Remove-exiting-on-unknown-option.patch

%description
ZLIB DATA COMPRESSION LIBRARY
zlib 1.2.11 is a general purpose data compression library.  All the code is
thread safe.  The data format used by the zlib library is described by RFCs
(Request for Comments) 1950 to 1952 in the files
http://tools.ietf.org/html/rfc1950 (zlib format), rfc1951 (deflate format) and
rfc1952 (gzip format).

%package bin
Summary: bin components for the optipng package.
Group: Binaries
Requires: optipng-license = %{version}-%{release}

%description bin
bin components for the optipng package.


%package license
Summary: license components for the optipng package.
Group: Default

%description license
license components for the optipng package.


%package man
Summary: man components for the optipng package.
Group: Default

%description man
man components for the optipng package.


%prep
%setup -q -n optipng-0.7.7
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1553910547
export LDFLAGS="${LDFLAGS} -fno-lto"
%configure --disable-static --with-system-libs
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
export SOURCE_DATE_EPOCH=1553910547
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/optipng
cp LICENSE.txt %{buildroot}/usr/share/package-licenses/optipng/LICENSE.txt
cp src/libpng/LICENSE %{buildroot}/usr/share/package-licenses/optipng/src_libpng_LICENSE
cp src/libpng/contrib/gregbook/COPYING %{buildroot}/usr/share/package-licenses/optipng/src_libpng_contrib_gregbook_COPYING
cp src/libpng/contrib/gregbook/LICENSE %{buildroot}/usr/share/package-licenses/optipng/src_libpng_contrib_gregbook_LICENSE
cp src/zlib/contrib/dotzlib/LICENSE_1_0.txt %{buildroot}/usr/share/package-licenses/optipng/src_zlib_contrib_dotzlib_LICENSE_1_0.txt
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/optipng

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/optipng/LICENSE.txt
/usr/share/package-licenses/optipng/src_libpng_LICENSE
/usr/share/package-licenses/optipng/src_libpng_contrib_gregbook_COPYING
/usr/share/package-licenses/optipng/src_libpng_contrib_gregbook_LICENSE
/usr/share/package-licenses/optipng/src_zlib_contrib_dotzlib_LICENSE_1_0.txt

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/optipng.1
